#----------------------------------------------------------------------
# This file was generated by img2py.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

icon = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAB6FJ"
    "REFUWIW1Vn9MFOkZfnaXBZbiZtUuuDgsIgR7Y0/UtQr+YMHQP2qtGvmW1r0CQvE0ERc9gUiw"
    "MULJ5TAeVNHE82IUtaU6NE3kDDVb6k/CpVkiGAfUDQ0y7KoDui7s4iy7O/3jHLvnYQBbn39m"
    "5pt53/d53++Z9/2AGYBhGBkApKam/phhmOWha9L1g4LjOAUAKJXKrQUFBQMsy8ql4DzPh42O"
    "jv6mtLR01gcjJAU8ePDgPJPJNCEIQq70rqen51Oz2Tw8NjYW8cEIhJIoLS29vmvXLhsA+Hw+"
    "tdlsHmlqavoDAPA8HzZdf/KZElCr1TIAqKys/Hp4eHh5Y2Pjz1paWj7z+Xxzrl69egIAbty4"
    "EZiuv2kzldDZ2RkEgPb29qvh4eHPu7q6LoyOjiZmZmb+saSkxMlxnIKiqGkTeC9IJT537lwt"
    "IUTMy8vjVq1aFQfMfO9nvAWh8Hg8KgBQKpWeW7dujb2PjxkTsFqtSq1W6x8cHMxvb2/fp1Ao"
    "vG63O+XEiROfA4DRaFS8D5FpQSp9QUHButzcXIEQErh586YlLy/PQQgR58yZsyn0u+lgygpw"
    "HKeQGo1Wq/Xb7faPg8HgX4LBYHhWVtaxjIyMY5s3bz4JABs3bjxRUVGxUKvV+qWm9T8ToCgq"
    "kJaWJtdqtf7u7u4lNTU1rePj47qEhIRrixYtqmBZVq7RaL6YP3/+Da/XS3m93gunT5/+EUVR"
    "AZ7nw6YS5ZQEvF7vr3Nzc2dt27Yto66u7h8ej0cfGxvb6ff7SXZ29oRarZZlZ2dPeDye30VF"
    "RXFPnjxJt9vtzZJWpvL/TnZutztcrVb7ysrK2lwul14QBM34+LhOr9dbFQrFr/bt25e8ZcsW"
    "3Z49e3pUKtUzQohYW1u76v79+1d9Pt+cpUuXnk9JSbHHxcW9WLt27fF39YcfVIDjOAXHcQq1"
    "Wu3z+/3aV69ezXK5XB+Nj4/r1qxZc/LLL7/8uVarPW6xWO7p9fq/X7lyZaC3t7dJp9PNr6qq"
    "+jY5OfmXkZGRT+7evZt36dKlw8FgUAYAGo1mUmHKQgMD3+05ALhcrm27d+9uEAQhRiaTBY4f"
    "P7593rx5FxITEzcYDIZvKioqdiuVykBDQ0Olx+NJ0Gg07NjYWHZzc7MzJycnOSYmppnnecPs"
    "2bPvFxUVfZKent7N83wYz/NBmqaDbyrAMIyMZVl5Z2dnkKKoQHd39xKLxXKzuLj4TzKZLBgT"
    "E/MvURQVNpvtPgDs2LHDpNPp7qxcufLksmXLTj169GhpXFzcTZfLRaelpVUBQEtLiz09Pb3t"
    "dSIp9fX13w4MDBRImgj9Q+QAQNN0cPXq1YsrKyv/VlNT0/3s2bNlWVlZDXK5PCknJ+fPAFBY"
    "WEgBQH9//6oFCxbcA4D8/Pyojo4OV0pKShkAdHV1bRIEIRoAOjo6fqFSqRy3b9/eGh0dPbB/"
    "//6zhw4dai4uLlZTFBWQpqrcaDQqqqqq/mqxWO45nc4lFouldNOmTQlZWVn7m5qavENDQ3MB"
    "4OHDh9EAMDY2Nl+v1zsA4OjRoz6GYWTr16+3aTSaXq/XSykUCpXb7Q5/8eLFRyqVatjpdLb6"
    "/f5lZrP5YG9v7+b4+HjObrcX0jQdZBhGJi8sLFQaDAZbUlLS6rNnzy7MyMg4Zjabn+v1eiUA"
    "jIyMzAaA0dFRJQDI5fLAy5cvo6US0jQto2k6qFKpRgDIgsGg0NfXNy8QCKgiIiLcEtGtW7fW"
    "PnjwIN5oNH514MCBM0eOHPmKECKGtba2jre2ttYC300yo9Go4Hk++Pjx4wkAcDgcCwFg7ty5"
    "AgCo1ep/9/b2LgUAlUqloGnab7ValU1NTQkqlWooPDzczTBMMgBERkaOAYAgCCLHcYrOzs4R"
    "QshnOp3uKE3T8W80wPN8GMdxCkKIqNVq/SzLijRNBwVBiH769OliACgtLR0CgBUrVlgHBgay"
    "z58/HxsdHS2R2uH1euM3bNjwNQDcuXMnEgD8fr8SANxut0hRVICmaRnHcQqn0zlUXV3dCbw+"
    "kLzdsdLS0uQAAtu3b18+MTERHxUVNZiamnoPADIzMy+0tbWVXbt2rau6uvqfTqfzJ3V1dYak"
    "pKRvLl68+AUAGAwGYXBwEIIgzAIAlmVFSeyvn9+If9JWHBERIQOAdevWbQGAxYsXXyspKXlp"
    "tVqVycnJ95RKZZZWq2X7+/tXR0REuBsbG/PKysq21NXVCQBQX18/+lqwcfn5+VGEEDF0JtA0"
    "/b1e8D1IHw4PD88uKCgYIISI2dnZ64H/TsbJ7FiWlUuZ7dy5c67ZbH5OCBHtdvvHku1kdj+o"
    "gHSgcDgcJo/Ho09MTGyzWq3tDMPIKIoKEEJEqV0zDCOT7iXdMAwjO3Xq1EhsbGwXAFy/fv23"
    "ANDX1yefcjpKL8vLyyOLiooeEEICDofjp1KG7zQMgZQpz/OfEEJEk8k0YbPZdoX6n9L4zJkz"
    "nxNCRFEUSej6dCEFamhoaCSEiIQQsaSk5I7f7zfZbLaYSclICzzPh+3du7e9p6fn0/cJ/ra/"
    "xMTEDYcPH76Yl5c3ZDKZfJcvX/49MM2KTrfs7yIQas+yrLy8vDxy2sbvm/nbkEQa6vv/4XfG"
    "YBhGNlnw/wCwPMDbTdEw7AAAAABJRU5ErkJggg==")
geticonData = icon.GetData
geticonImage = icon.GetImage
geticonBitmap = icon.GetBitmap
geticonIcon = icon.GetIcon

